flags: {}
packages:
- '.'
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Cartesian
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Leibniz
- location: C:/Users/Jonatan/Desktop/Haskell/modules/cubist-sculptor
- location: C:/Users/Jonatan/Desktop/Haskell/modules/chainable-operators
# - location: C:/Users/Jonatan/Desktop/Haskell/modules/abbey-road
extra-deps:
- GPipe-2.2.1
- GPipe-GLFW-1.4.1
- gl-0.8.0
# - ALUT-2.4.0.2
# - OpenAL-1.7.0.4
compiler-check: newer-minor
arch: x86_64
resolver: lts-7.0
