flags: {}
packages:
- '.'
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Cartesian
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Michelangelo
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Leibniz
extra-deps:
- GLUtil-0.9.1.0
- hpp-0.3.1.0
- pqueue-1.3.1.1
- reactive-banana-1.1.0.1
- storable-tuple-0.0.3.2
compiler-check: newer-minor
arch: x86_64
resolver: lts-7.0
