compiler-check: newer-minor
extra-deps:
- GLUtil-0.9.1.0
- hpp-0.3.1.0
- reactive-banana-1.1.0.1
- pqueue-1.3.1.1
- FTGL-2.1
- stb-truetype-0.1.2

resolver: lts-6.10
flags: {}
arch: i386, x86_64
# arch: i386, x86_62
packages:
- '.'
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Cartesian
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Michelangelo

# - location: C:/Users/Jonatan/Desktop/Haskell/projects/Pixels/libs/awesomium
# - location: C:/Users/Jonatan/Desktop/Haskell/projects/Pixels/libs/awesomium-raw
