compiler-check: newer-minor
extra-deps:
  - GLUtil-0.9.1.0
  - hpp-0.3.1.0
  - reactive-banana-1.1.0.1
  - pqueue-1.3.1.1
  - FTGL-2.1
  - stb-truetype-0.1.2
  # - QuadTree-0.11.0
  - friday-0.2.2.0
  - ratio-int-0.1.2
  - ClassyPrelude-0.1
  - storable-tuple-0.0.3.2
  - storable-record-0.0.3.1
resolver: lts-6.10
flags: {}
arch: x86_64
packages:
- '.'
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Cartesian
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Michelangelo
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Leibniz

# - location: C:/Users/Jonatan/Desktop/Haskell/projects/Pixels/libs/awesomium
# - location: C:/Users/Jonatan/Desktop/Haskell/projects/Pixels/libs/awesomium-raw
