compiler-check: newer-minor
extra-deps:
- GLUtil-0.9.1.0
- hpp-0.3.1.0

resolver: lts-6.10
flags: {}
packages:
- '.'
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Cartesian
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Michelangelo
