flags: {}
packages:
- '.'
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Cartesian
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Leibniz
- location: C:/Users/Jonatan/Desktop/Haskell/modules/cubist-sculptor
extra-deps:
- GPipe-2.2.1
- GPipe-GLFW-1.4.0
- gl-0.8.0
compiler-check: newer-minor
arch: x86_64
resolver: lts-7.0
